import { TelemetryDataSource } from '@prisma/client';
import { TeltonikaSensorDefinition } from './teltonika-sensor.mapper';
import { TELTONIKA_FMC650_CAN_ADAPTER_PROFILE } from './teltonika-device-profile';

const profile = TELTONIKA_FMC650_CAN_ADAPTER_PROFILE;

export const TELTONIKA_FMC650_CORE_SENSOR_DEFINITIONS: TeltonikaSensorDefinition[] = [
  // Permanent I/O
  {
    vendorSensorId: '239',
    deviceProfile: profile,
    parameterCode: 'IGNITION',
    displayName: 'Ignition',
    unit: null,
    multiplier: 1,
    offset: 0,
    dataSource: TelemetryDataSource.DEVICE,
    signed: false,
    isActive: true,
  },

  // FMC650 CAN adapter elements.
  // IDs and units are intentionally device-profile scoped.
  {
    vendorSensorId: '14',
    deviceProfile: profile,
    parameterCode: 'TOTAL_ENGINE_HOURS',
    displayName: 'Engine Worktime',
    unit: 'h',
    multiplier: 1 / 60,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
  {
    vendorSensorId: '15',
    deviceProfile: profile,
    parameterCode: 'TOTAL_ENGINE_HOURS_COUNTED',
    displayName: 'Engine Worktime Counted',
    unit: 'h',
    multiplier: 1 / 60,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
  {
    vendorSensorId: '16',
    deviceProfile: profile,
    parameterCode: 'TOTAL_DISTANCE_COUNTED',
    displayName: 'Total Mileage Counted',
    unit: 'km',
    multiplier: 0.001,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
  {
    vendorSensorId: '17',
    deviceProfile: profile,
    parameterCode: 'TOTAL_FUEL_USED_COUNTED',
    displayName: 'Fuel Consumed Counted',
    unit: 'L',
    multiplier: 0.1,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
  {
    vendorSensorId: '18',
    deviceProfile: profile,
    parameterCode: 'FUEL_RATE',
    displayName: 'Fuel Rate',
    unit: 'L/h',
    multiplier: 0.1,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
  {
    vendorSensorId: '23',
    deviceProfile: profile,
    parameterCode: 'ENGINE_LOAD',
    displayName: 'Engine Load',
    unit: '%',
    multiplier: 1,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
  {
    vendorSensorId: '25',
    deviceProfile: profile,
    parameterCode: 'ENGINE_TEMPERATURE',
    displayName: 'Engine Temperature',
    unit: '°C',
    multiplier: 0.1,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: true,
    isActive: true,
  },
  {
    vendorSensorId: '30',
    deviceProfile: profile,
    parameterCode: 'VEHICLE_SPEED',
    displayName: 'Vehicle Speed',
    unit: 'km/h',
    multiplier: 1,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
  {
    vendorSensorId: '31',
    deviceProfile: profile,
    parameterCode: 'ACCELERATOR_PEDAL_POSITION',
    displayName: 'Accelerator Pedal Position',
    unit: '%',
    multiplier: 1,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
  {
    vendorSensorId: '33',
    deviceProfile: profile,
    parameterCode: 'TOTAL_FUEL_USED',
    displayName: 'Fuel Consumed',
    unit: 'L',
    multiplier: 0.1,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
  {
    vendorSensorId: '34',
    deviceProfile: profile,
    parameterCode: 'FUEL_LEVEL_L',
    displayName: 'Fuel Level Liters',
    unit: 'L',
    multiplier: 0.1,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
  {
    vendorSensorId: '35',
    deviceProfile: profile,
    parameterCode: 'ENGINE_RPM',
    displayName: 'Engine RPM',
    unit: 'rpm',
    multiplier: 1,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
  {
    vendorSensorId: '36',
    deviceProfile: profile,
    parameterCode: 'TOTAL_DISTANCE',
    displayName: 'Total Mileage',
    unit: 'km',
    multiplier: 0.001,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
  {
    vendorSensorId: '37',
    deviceProfile: profile,
    parameterCode: 'FUEL_LEVEL_PERCENT',
    displayName: 'Fuel Level Percent',
    unit: '%',
    multiplier: 1,
    offset: 0,
    dataSource: TelemetryDataSource.ECU_CAN,
    signed: false,
    isActive: true,
  },
];

export function getTeltonikaFmc650CoreSensorDefinition(
  avlId: number | string,
): TeltonikaSensorDefinition | undefined {
  return TELTONIKA_FMC650_CORE_SENSOR_DEFINITIONS.find(
    (definition) => definition.vendorSensorId === String(avlId),
  );
}
