# fly.toml app configuration file generated for fleetfuelpro-backend on 2026-07-30T22:54:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fleetfuelpro-backend'
primary_region = 'nrt'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'
  seed_command = 'node seed.js'

[processes]
  app = 'npm run start:prod'

[env]
  MQTT_ENABLED = "true"
  MQTT_HOST = "s0136cff.ala.eu-central-1.emqxsl.com"
  MQTT_PORT = "8883"
  MQTT_TOPIC_TELEMETRY = "BCE/D"

  TELTONIKA_TCP_ENABLED = "true"
  TELTONIKA_TCP_HOST = "0.0.0.0"
  TELTONIKA_TCP_PORT = "5027"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 5027
  processes = ['app']
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 5027

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
